### ISSUE TITLE
Release image based on debian 11 (use of bitnami/minideb:bullseye as base image instead of bitnami/minideb:buster)

### ISSUE THREAD

**Issue by haddiwi** [bitnami/bitnami-docker-kube-state-metrics#4]
### Name and Version

bitnami/kube-state-metrics:2.0.0

### What is the problem this feature will solve?

This feature will solve secutiry critical vulnerabilities, below the trivy scan : 

For bitnami/kube-state-metrics:2.0.0 that use minideb:buster
![image](https://user-images.githubusercontent.com/104500554/165739595-6b06a668-fb2d-4811-bba8-6096c10ba400.png)

For minideb:bullseye 👍 
![image](https://user-images.githubusercontent.com/104500554/165740278-9445e8fc-3e48-4c1d-bc25-6accdaca8b77.png)

### What is the feature you are proposing to solve the problem?

Use bitnami/minideb:bullseye instead of bitnami/minideb:buster in Dockerfile 
![image](https://user-images.githubusercontent.com/104500554/165740787-48a33756-36c5-4908-a8a9-607016b53d52.png)

**Comment by carrodher** [comment]
Hi, unfortunately, as you rightly said, those security vulnerabilities are not fixed by the OS itself, so although we built the images on a daily basis to provide the latest version of system packages, this kind of CVE will be reported while there is no new version patching the issue in the OS.

Moving our base image from Debian 10 to 11 is something we are working on at this moment but I can't provide an ETA at this moment.
